### ISSUE TITLE
maskUrl doesn't seem to work

### ISSUE THREAD

**Issue by Kernonen** [frogcat/leaflet-tilelayer-mask#1]
Thank you very much for this great plug in. It works perfectly well with the default circular mask (even if smoother edges would be great) but I didn't manage to make it work with an external .png. 
Is there any special care needed when creating this png ? A special folder where to drop it ? 
Let us know !

**Comment by frogcat** [comment]
Thank you for your interest.
I wrote two samples to test behavior, so please let me know whether they work no not.
In my environment (Windows10, Chrome79), they seem to work well as shown in screenshots below.

# 1. relative URL

<https://bl.ocks.org/frogcat/raw/509368712d44e8430a32f9ba5553f18d/index.html>

![image](https://user-images.githubusercontent.com/12029629/71055484-22749500-2199-11ea-8d95-5b41c8900a95.png)


* [star.png](https://bl.ocks.org/frogcat/raw/509368712d44e8430a32f9ba5553f18d/star.png) is set as maskUrl

# 2. absolute (external) URL

<https://bl.ocks.org/frogcat/raw/509368712d44e8430a32f9ba5553f18d/external.html>

![image](https://user-images.githubusercontent.com/12029629/71055506-3ae4af80-2199-11ea-916f-315c15763d1b.png)

* <https://i0.wp.com/mirrors.creativecommons.org/presskit/logos/cc.logo.png> is set as maskUrl

**Comment by Kernonen** [comment]
Hello ! 
Thanks for your fast answer ! 
It doesn’t seem to work local for me. 
Do I have to take special precautions when creating the .png ? Is it png-8 ou png-24 ? Any size limitations ? 
Laurent

**Comment by Kernonen** [comment]
I wonder if there's not a problem with my elements hierarchy in the folder. Could you post the folder of your relative url example see where .png is stored ?

**Comment by frogcat** [comment]
Clone <https://gist.github.com/frogcat/509368712d44e8430a32f9ba5553f18d> and check file structure.

**Comment by Kernonen** [comment]
Thank you Yuzo ! 
I got it right ! My problem came from the nature of the png itself. Mine was only a black circle on a transparent background. So it couldn’t work. 
I would like the mask to stay in the center of the view window when I scroll the map. Do you have an idea how I can do that ?

**Comment by frogcat** [comment]
That's good. I'll update README.md later to add note about maskUrl. 

> I would like the mask to stay in the center of the view window when I scroll the map. Do you have an idea how I can do that ?

Try this code.


```after.js

/* comment out to ignore  mousemove event
// Add event handler to update mask position
 map.on("mousemove", function(e) {
  fg.setCenter(e.containerPoint);
 });
*/

// add move event listener to update mask's center to fit map's center
map.on("move", function() {
 fg.setCenter(map.latLngToContainerPoint(map.getCenter()));
});
```

**Comment by Kernonen** [comment]
thank you for the code !
but actually, i’m looking for the mask to stay in the middle of the screen when the map moves. like a looking glass

**Comment by frogcat** [comment]
I have no idea.
[Minimaps & synced maps](https://leafletjs.com/plugins.html#minimaps--synced-maps) plugins may be useful.

**Comment by Kernonen** [comment]
I mange to achieve the effect I needed.
If it might help :

		var height = (document.getElementById('map').clientHeight)/2;
		var width = (document.getElementById('map').clientWidth)/2;
		map.on("move", function() {
				mask.setCenter(width, height)
		});	

Thanks anyway for your wonderful work
Laurent
